[package]
name = "tract-tensorflow"
version = "0.5.12-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks", "ONNX" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
bytes = "0.5"
derive-new = "0.5"
itertools = "0.8"
log = "0.4"
prost = "0.6"
prost-types = "0.6"
tensorflow = { version = "0", optional = true }
tract-hir = { path = "../hir" }

[build-dependencies]
prost-build = "0.6"

[features]
conform = [ "tensorflow" ]

[dev-dependencies]
criterion = "0.3"
env_logger = "0.7"
proptest = "0.9"
rand = "0.7"

# [[bench]]
# name = "conv"
# harness = false
